// This code was generated by `SqlHydra.SqlServer` -- v3.4.0.
namespace SqlHydraForSqlite

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(3, 4, 0)
    let ns = "SqlHydraForSqlite"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module dbo =

    [<CLIMutable>]
    type SqliteDateTest =
        { [<ProviderDbType("Date")>]
          date: System.DateOnly }

    let SqliteDateTest = table<SqliteDateTest>

    [<CLIMutable>]
    type SqliteDateTime2Test =
        { [<ProviderDbType("DateTime2")>]
          dt: System.DateTime }

    let SqliteDateTime2Test = table<SqliteDateTime2Test>


[<System.Obsolete("The HydraReader module is no longer needed and will be removed in v4.0.")>]
type HydraReader =
    static member Read(reader: Microsoft.Data.SqlClient.SqlDataReader) : (unit -> 'T) =
        Hydration.buildRowReader<'T> Domain.ProviderType.SqlServer reader


[<System.Obsolete("The HydraBuilders module is no longer needed and will be removed in v4.0.")>]
module HydraBuilders =
    ()


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let compiler = SqlKata.Compilers.SqlServerCompiler()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.SqlClient.SqlConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
